# Generated by Django 3.1.1 on 2020-09-20 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='unit',
        ),
        migrations.AddField(
            model_name='productlist',
            name='description',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductsInProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=100)),
                ('unit', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('productList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productlist')),
            ],
        ),
    ]
