# Generated by Django 3.1.1 on 2020-09-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200920_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unitPrice',
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=100),
            preserve_default=False,
        ),
    ]
